# Generated by Django 5.1.3 on 2024-12-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_staff_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('delete_customer', 'Can delete users')]},
        ),
    ]
