# Generated by Django 5.1.3 on 2025-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='sender',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='name',
        ),
        migrations.AlterField(
            model_name='emails',
            name='type',
            field=models.TextField(default='Potential Cust', max_length=120),
        ),
    ]
