# Generated by Django 5.1.3 on 2025-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_rename_sender_emails_email_remove_emails_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
