# Generated by Django 5.1.3 on 2025-03-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_emails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emails',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
