# Generated by Django 5.1.3 on 2025-02-24 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combmodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='monthly_market_cost',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketingtype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='user',
        ),
        migrations.CreateModel(
            name='ClientSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_name', models.CharField(max_length=255)),
                ('number_of_clients', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAcquisitionCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_ads', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('google_ads', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_cost_per_click', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leads_generated', models.IntegerField(blank=True, null=True)),
                ('percentage_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other_marketing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offline_customers_acquired', models.IntegerField(blank=True, null=True)),
                ('organic_customers_acquired', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_ads', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('google_ads', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('physical_marketing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_boards', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_marketing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_subscribers', models.IntegerField(blank=True, null=True)),
                ('subscriber_1_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('subscriber_2_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('marketing_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combmodels.marketingcost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Marketing',
        ),
        migrations.DeleteModel(
            name='MarketingType',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
