# Generated by Django 5.1.3 on 2025-01-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
