# Generated by Django 5.1.3 on 2025-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_alter_revenuemodel_percentage_comm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuemodel',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
