# Generated by Django 5.1.3 on 2025-06-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_revenuestream_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuedrivers',
            name='revenue_streams',
        ),
        migrations.AlterField(
            model_name='revenuestream',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_streams', to='financials.revenuedrivers'),
        ),
    ]
