# Generated by Django 5.1.3 on 2025-03-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingmetrics',
            old_name='number_of_customers',
            new_name='new_monthly_customers',
        ),
    ]
