# Generated by Django 5.1.3 on 2025-03-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_rename_number_of_customers_marketingmetrics_new_monthly_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingmetrics',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='growth_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketingmetrics',
            name='monthly_marketing_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
