# Generated by Django 5.1.3 on 2025-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_marketingmetrics_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmetrics',
            name='new_monthly_customers',
            field=models.PositiveIntegerField(),
        ),
    ]
