# Generated by Django 5.1.3 on 2025-03-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_marketingmetrics_new_monthly_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcomponent',
            name='marketing_metrics',
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='marketing_components',
            field=models.ManyToManyField(to='marketing.marketingcomponent'),
        ),
    ]
