# Generated by Django 5.1.3 on 2025-03-20 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_remove_marketingcomponent_marketing_metrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmetrics',
            name='cac',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.RemoveField(
            model_name='marketingmetrics',
            name='growth_rate',
        ),
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='growth_rate',
            field=models.ManyToManyField(to='marketing.growthrate'),
        ),
    ]
