# Generated by Django 5.1.3 on 2025-03-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_marketingmetrics_cac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingmetrics',
            name='number_of_months_in_year',
        ),
    ]
