# Generated by Django 5.1.3 on 2025-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_remove_marketingmetrics_number_of_months_in_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmetrics',
            name='yearly_marketing_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
