# Generated by Django 5.1.3 on 2025-06-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_marketingmetrics_yearly_marketing_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrate',
            name='marketing_metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_rates', to='marketing.marketingmetrics'),
        ),
        migrations.AddField(
            model_name='marketingcomponent',
            name='market_metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='marketing.marketingmetrics'),
        ),
    ]
