# Generated by Django 5.1.3 on 2025-06-11 18:16

from django.db import migrations

def transfer_relationships(apps, schema_editor):
    MarketingMetrics = apps.get_model('marketing', 'MarketingMetrics')
    
    # Process all MarketingMetrics instances
    for metrics in MarketingMetrics.objects.all():
        # Transfer GrowthRate relationships
        growth_rates = metrics.growth_rate.all()
        for growth_rate in growth_rates:
            growth_rate.marketing_metrics = metrics
            growth_rate.save()
            
        # Transfer MarketingComponent relationships
        components = metrics.marketing_components.all()
        for component in components:
            component.market_metrics = metrics
            component.save()

def reverse_relationships(apps, schema_editor):
    MarketingMetrics = apps.get_model('marketing', 'MarketingMetrics')
    GrowthRate = apps.get_model('marketing', 'GrowthRate')
    MarketingComponent = apps.get_model('marketing', 'MarketingComponent')
    
    # Reverse all relationships
    for metrics in MarketingMetrics.objects.all():
        # Restore GrowthRate M2M relationships
        growth_rates = metrics.growth_rates.all()
        for growth_rate in growth_rates:
            metrics.growth_rate.add(growth_rate)
            growth_rate.marketing_metrics = None
            growth_rate.save()
            
        # Restore MarketingComponent M2M relationships
        components = metrics.components.all()
        for component in components:
            metrics.marketing_components.add(component)
            component.market_metrics = None
            component.save()

class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_growthrate_marketing_metrics_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_relationships, reverse_relationships),
    ]