# Generated by Django 5.1.3 on 2024-12-15 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalExpenditure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_capex', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth_capex', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset_lifespan', models.PositiveIntegerField()),
                ('capitalized_costs', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_growth', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('industry_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('competitor_count', models.PositiveIntegerField()),
                ('market_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('corporate_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gdp_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueExpenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('direct_labor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('manufacturing_overhead', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salaries', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marketing', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technology', models.DecimalField(decimal_places=2, max_digits=15)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_operating_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingCapital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_receivables', models.PositiveIntegerField()),
                ('days_inventory', models.PositiveIntegerField()),
                ('days_payables', models.PositiveIntegerField()),
                ('working_capital_days', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('Land', 'Land'), ('Buildings', 'Buildings'), ('Machinery', 'Machinery'), ('Vehicles', 'Vehicles'), ('Equipment', 'Equipment'), ('Furniture', 'Furniture'), ('Technology', 'Technology'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('capital_expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_assets', to='financials.capitalexpenditure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Rent', 'Rent'), ('Marketing', 'Marketing'), ('Subscription', 'Subscription'), ('Accounting', 'Accounting'), ('Legal', 'Legal'), ('Utility', 'Utility'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_salary_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_expenses', to='financials.employeesalaryinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('count', models.PositiveIntegerField()),
                ('employee_salary_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='financials.employeesalaryinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
