# Generated by Django 5.1.3 on 2024-12-19 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMarketingExp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exp_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllExpenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.PositiveIntegerField()),
                ('admin_marketing_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.adminmarketingexp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_capex', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth_capex', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset_lifespan', models.PositiveIntegerField()),
                ('capitalized_costs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('assets', models.ManyToManyField(to='financials.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('company_stage', models.CharField(max_length=25)),
                ('funding_type', models.CharField(max_length=25)),
                ('fiscal_year_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostStracture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_material', models.DecimalField(decimal_places=2, max_digits=15)),
                ('direct_labor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('man_overhead', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cogs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fixed_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variable_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cd_raw_material', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cd_direct_labor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cd_man_overhead', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DividendPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('div_per_share', models.DecimalField(decimal_places=2, max_digits=4)),
                ('div_growth_rt', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.PositiveIntegerField()),
                ('salary_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salaries', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marketing', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technology', models.DecimalField(decimal_places=2, max_digits=15)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_operating_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_equivs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acc_receivable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fixed_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acc_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_in_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retained_earning', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueDrivers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='adminexpense',
            name='employee_salary_info',
        ),
        migrations.RemoveField(
            model_name='capitalasset',
            name='capital_expenditure',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='employee_salary_info',
        ),
        migrations.DeleteModel(
            name='RevenueExpenses',
        ),
        migrations.AddField(
            model_name='allexpenses',
            name='employee_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.employeeinfo'),
        ),
        migrations.AddField(
            model_name='revenuedrivers',
            name='revenue_streams',
            field=models.ManyToManyField(to='financials.revenuestream'),
        ),
        migrations.DeleteModel(
            name='AdminExpense',
        ),
        migrations.DeleteModel(
            name='CapitalAsset',
        ),
        migrations.DeleteModel(
            name='CapitalExpenditure',
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryInfo',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
