# Generated by Django 5.1.3 on 2025-01-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_rename_user_adminmarketingexp_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmarketingexp',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='allexpenses',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='capex',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='companyinformation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='coststracture',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dividendpolicy',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalfindata',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='industrymetrics',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='revenuedrivers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='revenuestream',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workingcapital',
            old_name='user_id',
            new_name='user',
        ),
    ]
