# Generated by Django 5.1.3 on 2025-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_adminmarketingexp_user_alter_allexpenses_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuedrivers',
            name='average_selling_price',
        ),
        migrations.AddField(
            model_name='revenuedrivers',
            name='percentage_comm',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
