# Generated by Django 5.1.3 on 2025-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_remove_revenuedrivers_average_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allexpenses',
            name='average_selling_price',
        ),
        migrations.RemoveField(
            model_name='allexpenses',
            name='units_sold',
        ),
        migrations.AddField(
            model_name='allexpenses',
            name='salary_growth_rate',
            field=models.DecimalField(decimal_places=2, default=2.1, max_digits=5),
            preserve_default=False,
        ),
    ]
