# Generated by Django 5.1.3 on 2025-04-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_remove_allexpenses_average_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuedrivers',
            name='q1',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
        migrations.AddField(
            model_name='revenuedrivers',
            name='q2',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
        migrations.AddField(
            model_name='revenuedrivers',
            name='q3',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
        migrations.AddField(
            model_name='revenuedrivers',
            name='q4',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
    ]
