# Generated by Django 5.1.3 on 2025-06-02 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_revenuestream_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuestream',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_streams_fk', to='financials.revenuedrivers'),
        ),
        migrations.AlterField(
            model_name='revenuedrivers',
            name='revenue_streams',
            field=models.ManyToManyField(related_name='drivers', to='financials.revenuestream'),
        ),
    ]
