# Generated by Django 5.1.3 on 2025-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_remove_revenuedrivers_revenue_streams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuestream',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='revenuestream',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='revenuestream',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
