# Generated by Django 5.1.3 on 2025-06-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_transfer_expense_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='capex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_items', to='financials.capex'),
        ),
        migrations.AlterField(
            model_name='capex',
            name='assets',
            field=models.ManyToManyField(related_name='capex_assets', to='financials.asset'),
        ),
    ]
