# Generated by Django 5.1.3 on 2025-06-11 19:14

from django.db import migrations

def transfer_relationships(apps, schema_editor):
    Capex = apps.get_model('financials', 'Capex')
    
    # Process all Capex instances
    for capex in Capex.objects.all():
        # Transfer Asset relationships
        assets = capex.assets.all()
        for asset in assets:
            asset.capex = capex
            asset.save()

def reverse_relationships(apps, schema_editor):
    Asset = apps.get_model('financials', 'Asset')
    
    # Reverse the relationships
    for asset in Asset.objects.all():
        if asset.capex:
            asset.capex.assets.add(asset)
            asset.capex = None
            asset.save()

class Migration(migrations.Migration):
    dependencies = [
        ('financials', '0012_asset_capex_alter_capex_assets'),
    ]

    operations = [
        migrations.RunPython(transfer_relationships, reverse_relationships),
    ]