# Generated by Django 5.1.3 on 2025-03-03 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.IntegerField(choices=[(1, 'FY1'), (2, 'FY2'), (3, 'FY3'), (4, 'FY4'), (5, 'FY5')])),
                ('beginning_monthly_clients', models.IntegerField()),
                ('additional_new_clients_per_month', models.IntegerField()),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('churn_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('churned_clients_per_month', models.IntegerField(editable=False)),
                ('closing_monthly_clients', models.IntegerField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPercentageDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.IntegerField(choices=[(1, 'FY1'), (2, 'FY2'), (3, 'FY3'), (4, 'FY4'), (5, 'FY5')])),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('closing_customers', models.IntegerField()),
                ('subscription_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('other_services_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
