# Generated by Django 5.1.3 on 2025-03-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='additional_new_clients_per_month',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='beginning_monthly_clients',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='churned_clients_per_month',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='closing_monthly_clients',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='growth_rate',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='beginning_client',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_type',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='organic_client',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='churn_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='CustomerPercentageDistribution',
        ),
    ]
