# Generated by Django 5.1.3 on 2025-03-25 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customermodel_additional_new_clients_per_month_and_more'),
        ('marketing', '0006_alter_marketingmetrics_cac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='marketing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingmetrics'),
            preserve_default=False,
        ),
    ]
