# Generated by Django 5.1.3 on 2025-03-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customermodel_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='growth_rate',
        ),
    ]
