# Generated by Django 5.1.3 on 2025-04-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customermodel_customer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='growth_rate',
        ),
    ]
