# Generated by Django 5.1.3 on 2025-04-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_churn_rate_churnrate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churnrate',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
