# Generated by Django 5.1.3 on 2025-04-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_churnrate_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='cust_distribution',
            new_name='cust_type',
        ),
    ]
