# Generated by Django 5.1.3 on 2025-06-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_cust_distribution_customermodel_cust_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdistribution',
            name='cust_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='customer.customermodel'),
        ),
    ]
