# Generated by Django 5.1.3 on 2025-05-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_cust_distribution_customermodel_cust_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='cust_type',
        ),
    ]
